name: speechkoo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_commons: ^0.9.0
  image_picker: ^1.1.2
  flutter_tts: ^4.2.0
  permission_handler: ^10.0.0
  flutter_launcher_icons: ^0.13.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true  # Enable icon generation for Android
  ios: true      # Enable icon generation for iOS
  image_path: "assets/logo.png"  # Path to your app icon image

assets:
    - assets/logo.png
